### ISSUE TITLE
v20.0.2 Can't login - null pointer

### ISSUE THREAD

**Issue by joshmartinlumi** [sventorben/keycloak-home-idp-discovery#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to log in with home idp discovery causes a null pointer exception.

Instance was setup on previous versions and just updated to latest, when bugged appear. Rolling back to 20.0.1 fixes issue.

### Expected Behavior

Log in works

### Steps To Reproduce

Latest (20.0.3) keycloak with 20.0.2 of home idp discovery
Start login journey
Enter email
Failure presents 
![image](https://user-images.githubusercontent.com/114989978/219008240-957b3db4-17b0-43ab-abf9-013198e66177.png)

### Version

```markdown
- Keycloak: 20.0.3
- This extension: 20.0.2
```

### Anything else?

2023-02-15 10:52:25,045 WARN  [org.keycloak.services] (executor-thread-0) KC-SERVICES0013: Failed authentication: java.lang.NullPointerException
        at de.sventorben.keycloak.authentication.hidpd.HomeIdpDiscoverer.discoverForUser(HomeIdpDiscoverer.java:38)
        at de.sventorben.keycloak.authentication.hidpd.HomeIdpDiscoveryAuthenticator.action(HomeIdpDiscoveryAuthenticator.java:52)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processAction(DefaultAuthenticationFlow.java:155)
        at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:977)
        at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:311)
        at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:282)
        at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:274)
        at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:339)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
        
        
Log dump
![image](https://user-images.githubusercontent.com/114989978/219008423-93b409c4-9cfb-43ab-b232-1d61215dd8b1.png)

**Comment by joshmartinlumi** [comment]
I feel this might be a bit sparse apologies, if theres more info I can provide, please let me know

**Comment by joshmartinlumi** [comment]
I had a little dig to see if I could see the culprit, I might have found it?

This logging was added two weeks ago, which calls context.getAuthenticatorConfig() which has the possibility of returning null.
src\main\java\de\sventorben\keycloak\authentication\hidpd\HomeIdpDiscoverer.java
![image](https://user-images.githubusercontent.com/114989978/219012345-ee6bb2c0-540f-4399-b812-dee9a8a30c9e.png)

services\src\main\java\org\keycloak\authentication\AuthenticationProcessor.java
![image](https://user-images.githubusercontent.com/114989978/219012512-5a651aee-9c54-4675-b7fe-6d15076c6edd.png)
Possibly the cause?

**Comment by sventorben** [comment]
Definitely caused by changes in c69407bce754fd4244a2caa0255e6a8bdc8b6182

**Comment by sventorben** [comment]
Fixed in release [20.0.3](https://github.com/sventorben/keycloak-home-idp-discovery/releases/tag/v2.0.3)
