### ISSUE TITLE
[BUG] Login page not reachable due to java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by marxeysm** [sventorben/keycloak-home-idp-discovery#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi and thanks for the module.
I've installed the module and configured it as shown in the README.md.
Here is my authentication flow :

![image](https://user-images.githubusercontent.com/127302814/234246680-ff27fa23-add5-4fc8-994e-b7a80aba794f.png)
I've added configured it as the default Browser flow of my realm.
Whenever I try to reach the login page, I get the following error page : 
![image](https://user-images.githubusercontent.com/127302814/234247011-bee1d8e0-187e-4b09-9e07-42231a38e447.png)
When I check the logs, this is what I get : 
`2023-04-25 10:02:59,292 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-23) Uncaught server error: java.lang.NoSuchMethodError: 'org.jboss.resteasy.spi.HttpRequest org.keycloak.authentication.AuthenticationFlowContext.getHttpRequest()'
        at de.sventorben.keycloak.authentication.hidpd.AuthenticationChallenge.challenge(AuthenticationChallenge.java:25)
        at de.sventorben.keycloak.authentication.hidpd.HomeIdpDiscoveryAuthenticator.authenticate(HomeIdpDiscoveryAuthenticator.java:34)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:445)
        at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:271)
        at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1025)
        at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:887)
        at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:153)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:363)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:219)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.access$300(AuthorizationEndpoint.java:69)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint$1.runInternal(AuthorizationEndpoint.java:140)
        at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:67)
        at org.keycloak.common.util.ResponseSessionTask.run(ResponseSessionTask.java:44)
        at org.keycloak.models.utils.KeycloakModelUtils.runJobInRetriableTransaction(KeycloakModelUtils.java:299)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.processInRetriableTransaction(AuthorizationEndpoint.java:132)
        at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:117)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
`
My version of Keycloak is 21.0.2 and I'm using the 21.0.1 release of the module. Is it the reason why I get this error ? Would the 21.1.0 version works, or should I upgrade my Keycloak version ?

Thanks ! 

### Expected Behavior

I should be redirected to the login page with a username/password form.

### Version

```markdown
- Keycloak: 21.0.2
- This extension: 21.0.1
```

**Comment by sventorben** [comment]
Hello @marxeysm,

thanks for reporting. That is an interesting one. It looks like a runtime incompatibility introduced by https://github.com/keycloak/keycloak/issues/15374.

However, version 21.0.1 of this extension should be compatible with Keycloak 21.0.2.

It is compiled with Keycloak 21.0.0 which already had that change. 
```shell
✔ /src/keycloak-home-idp-discovery [v21.0.1|…1⚑ 21]
16:43 $ mvn dependency:tree -Dverbose | grep keycloak
[INFO] ---------< de.sventorben.keycloak:keycloak-home-idp-discovery >---------
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ keycloak-home-idp-discovery ---
[INFO] de.sventorben.keycloak:keycloak-home-idp-discovery:jar:21.0.1
[INFO] +- org.keycloak:keycloak-core:jar:21.0.0:provided
[INFO] |  +- org.keycloak:keycloak-common:jar:21.0.0:provided
[INFO] +- org.keycloak:keycloak-server-spi:jar:21.0.0:provided
[INFO] +- org.keycloak:keycloak-server-spi-private:jar:21.0.0:provided
[INFO] +- org.keycloak:keycloak-services:jar:21.0.0:provided
[INFO] |  +- (org.keycloak:keycloak-core:jar:21.0.0:provided - omitted for duplicate)
[INFO] |  +- (org.keycloak:keycloak-common:jar:21.0.0:provided - omitted for duplicate)
[INFO] +- com.github.dasniko:testcontainers-keycloak:jar:2.5.0:test
[INFO] |  \- (org.keycloak:keycloak-admin-client:jar:21.0.0:test - omitted for duplicate)
[INFO] +- org.keycloak:keycloak-admin-client:jar:21.0.0:test
[INFO] |  +- (org.keycloak:keycloak-core:jar:21.0.0:test - omitted for duplicate)
[INFO] |  +- (org.keycloak:keycloak-common:jar:21.0.0:test - omitted for duplicate)
```

I had that exact exception in a compatiblity test (see [logs for details](https://github.com/sventorben/keycloak-home-idp-discovery/actions/runs/4256141451/jobs/7404644489#step:4:4478)). This is why versions >=21 of this extension are no longer compatible with versions <21 of Keycloak.

Can you please reconfirm that you are using version 21.x and not a version 20.x of this extension?

**Comment by marxeysm** [comment]
Thanks for the quick answer ! 

The module version was indeed the wrong one, a previous 20.0.1 version had been set up in the docker container where Keycloak is hosted, and as I was restarting the container after copying the 21.0.1 module version into it, the 20.0.1 was erasing the 21.0.1 I just copied. I modified the docker-compose and everything is fine now. 

Thanks for the help and sorry for the trouble ! Have a nice day
