### ISSUE TITLE
[BUG] Password form step is ignored when user enters non matching domain email address

### ISSUE THREAD

**Issue by tanalam2411** [sventorben/keycloak-home-idp-discovery#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After setting home-idp-discovery-flow as default browser flow, within a realm with following steps in following order:

1. Cookie (Alternative)
2. Home IdP Discovery (Alternative)
3. Password Form (Alternative)

When user trys to login with the matching domain configured as per configured Identity provider, it redirects to IDP login page.
But when user's email doesn't have matching domain, it should take user to passform form, buts it directly fails with msg `Invalid username or password.` instead of showing the password form.

Its configured in OpenShift under RHBK version 24.0.7 with keycloak-home-idp-discovery v24.0.0

Error logs
```
2024-09-21 16:18:54,895 INFO [de.sventorben.keycloak.authentication.hidpd.HomeIdpDiscoverer] (executor-thread-14731) Could not find home IdP for domain 'sample.com' and user 'benzema@sample.com' in realm 'nm'
2024-09-21 16:18:54,896 WARN [org.keycloak.services] (executor-thread-14731) KC-SERVICES0013: Failed authentication: org.keycloak.authentication.AuthenticationFlowException
at org.keycloak.authentication.AuthenticationProcessor.authenticationAction(AuthenticationProcessor.java:1014)
at org.keycloak.services.resources.LoginActionsService.processFlow(LoginActionsService.java:370)
at org.keycloak.services.resources.LoginActionsService.processAuthentication(LoginActionsService.java:341)
at org.keycloak.services.resources.LoginActionsService.authenticate(LoginActionsService.java:333)
at org.keycloak.services.resources.LoginActionsService.authenticateForm(LoginActionsService.java:398)
at org.keycloak.services.resources.LoginActionsService$quarkusrestinvoker$authenticateForm_32b8e198ac3110abd1d5774e83a4cf87858129f4.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:840)
2024-09-21 16:18:54,896 WARN [org.keycloak.events] (executor-thread-14731) type="LOGIN_ERROR", realmId="nm", clientId="account-console", userId="null",  error="invalid_user_credentials", auth_method="openid-connect", auth_type="code", redirect_uri="https://rhbk.apps.nm.kubeapp.cloud/realms/nm/account/", code_id="5fktb67", username="benzema@sample.com"
```

### Expected Behavior

When user trys to login with the matching domain configured as per configured Identity provider, it should redirect to matching IDP login page (Working).
When user enters email different then matching domain, it should take user to password form and allow user to enter password. (Not working)

### Version

```markdown
- Keycloak: 24.0.7
- This extension: v24.0.0
```

### Anything else?

![image](https://github.com/user-attachments/assets/201eea0b-3efd-48bd-b5de-5fa1e3e37ffb)

**Comment by sventorben** [comment]
Using the password form only is no longer supported since version 22.1.0 of this extension. You need to use a username&password authenticator instead.

**Comment by tanalam2411** [comment]
@sventorben In the configuration docs, it could be confusing for someone who is not familiar with keycloak's flow subflow concepts. 
I have created one PR https://github.com/sventorben/keycloak-home-idp-discovery/pull/428
Please review and approve if it make sence.
And for this issue, user and password form step worked.
