### ISSUE TITLE
[Enhancement] New Admin console

### ISSUE THREAD

**Issue by sventorben** [sventorben/keycloak-home-idp-discovery#86]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Is your feature related to a problem? Please describe.

With Keycloak 19 the new admin console became the default and the old one got deprecated. 

### Describe the solution you'd like

- [ ] Remove the current theme used to show configured email addresses
- [ ] Add a theme to configure email addresses via the new admin console
- [ ] Update readme accordingly
- [ ] Update screenshots

**Comment by sventorben** [comment]
see also https://github.com/keycloak/keycloak/discussions/13598#discussioncomment-3351961

**Comment by sventorben** [comment]
I will not work on this before the new admin console has some kind of extension mechanism that can be leveraged.

**Comment by ymakiev-sc** [comment]
Hello. After spending one day without any success I decided to ask. Could you please clarify is it compatible with keycloak 18.0.0?
I've tried to apply it, but it doesn't work for some reason. Docker image is "quay.io/keycloak/keycloak:18.0.0".
Also were added start commands like --spi-theme-cache-themes=false --spi-theme-cache-templates=false but it doesn't help.
I can see this custom theme in realm settings, but when I select it nothing happen. I checked that page `kc-tabs-identity-provider.html` still exists in keycloak source code with the same name, but it's not replaced to custom. 

Do you know what could it be?

**Comment by sventorben** [comment]
Hello @ymakiev-sc,

release [18.0.0](https://github.com/sventorben/keycloak-home-idp-discovery/releases/tag/v18.0.0) of this extension is compatible with Keycloak 18.x. All newer versions are incompatible due to some [changes to internal Keycloak APIs](https://www.keycloak.org/2022/07/keycloak-1900-released#_changes_in_keycloaksession)

With regards to the theme, make sure to set the theme in the master realm and not in one of your custom realms. Please reload the page afterwards.

Best regards
Sven-Torben

**Comment by ymakiev-sc** [comment]
The cause was related to master realm as you said, because I've tried to setup it for custom realm. Thanks a lot @sventorben!

**Comment by emmarichardson** [comment]
So, we cannot set a domain on later versions?  I have been unable to connect through the kcadmn.sh and the page in the console does not appear to exist...

**Comment by sventorben** [comment]
If you install a version of this plugin that is compatible with your Keycloak version everything should work as expected. You should be able to use the REST API or kcadm tool to set domains.

However, currently there is no way to extend the new admin console with custom tabs or editors. So, this will no longer be supported, because there is no way to implement it without forking the admin console.

**Comment by sventorben** [comment]
The old admin console has been removed with Keycloak version 21 (see. [release notes](https://www.keycloak.org/docs/latest/release_notes/index.html))
I have removed the old theme from my codebase as well.

**Comment by williancolognesitrimble** [comment]
@sventorben what can I do that make it works with keycloak 21, any workaround?
I'm facing the this error:

```
2023-02-24 20:18:47,400 ERROR [org.keycloak.theme.DefaultThemeManager] (executor-thread-18) Failed to find ADMIN theme keycloak, using built-in themes
2023-02-24 20:18:47,799 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-18) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.theme.Theme.getImportName()" because "theme" is null
	at org.keycloak.theme.DefaultThemeManager.loadTheme(DefaultThemeManager.java:119)
	at org.keycloak.theme.DefaultThemeManager.getTheme(DefaultThemeManager.java:68)
	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.setThemes(ServerInfoAdminResource.java:182)
	at org.keycloak.services.resources.admin.info.ServerInfoAdminResource.getInfo(ServerInfoAdminResource.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
```

**Comment by sventorben** [comment]
@williancolognesitrimble can you please try version 21.0.1.
I forgot to include the removal of the old admin theme with the previous release.

**Comment by fzoske** [comment]
@sventorben I can confirm, that the error is gone with 21.0.1

**Comment by sventorben** [comment]
For reference https://github.com/keycloak/keycloak/commit/bc74d4f0eb97fd450abc7225cc0e36f56b6de9b8

**Comment by sventorben** [comment]
For reference: https://github.com/keycloak/keycloak/issues/19969

**Comment by sventorben** [comment]
For reference: https://github.com/keycloak/keycloak/discussions/24805
