### ISSUE TITLE
Facing issue while using this.

### ISSUE THREAD

**Issue by ZaheerUdDeen** [sventorben/keycloak-home-idp-discovery#90]
I have added it into my keycloak as provider & configure provided steps as well. Now I am not sure how to use it. is it expected to work directly after this? by this I mean once I land to login page it will only show username/email field & worked further as expected?

**Comment by sventorben** [comment]
Hello @ZaheerUdDeen,

can you describe what issue you are facing, please?

If you have followed the steps in the [README](README.md) you should be fine.
You have to 
- copy the Provider jar
- create a custom flow and add the authenticator as needed
- bind that flow to your client either with default binding or authentication flow overrides
- add at least one identity provider
- configure email domains for the identity provider

After that, I'd expect this extension to work.

**Comment by sventorben** [comment]
Closing this issue due to missing feedback.

**Comment by nitin-vavdiya** [comment]
Hey, Do we need to bind this newly created flow with the browser flow?
 Flow: 
![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/45592624/f004a765-a86d-45d8-9d29-7f8f88d2a4c9)

 I bind this flow with the account console with the Browser flow. WhenI opening the account console login page it is giving internal server error:

Binding with account console:
![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/45592624/f01e1108-e603-441c-a0b1-926c13bb72ca)

Error:
  
![image](https://github.com/sventorben/keycloak-home-idp-discovery/assets/45592624/e10b7302-7a29-4bb0-a7d2-b28229dca18b)


Logs: 
```
2023-05-10 05:41:39,645 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-92) Uncaught server error: java.lang.NoSuchMethodError: 'org.keycloak.http.HttpRequest org.keycloak.authentication.AuthenticationFlowContext.getHttpRequest()'
	at de.sventorben.keycloak.authentication.hidpd.RememberMe.getUserName(RememberMe.java:45)
	at de.sventorben.keycloak.authentication.hidpd.AuthenticationChallenge.forceChallenge(AuthenticationChallenge.java:35)
	at de.sventorben.keycloak.authentication.hidpd.HomeIdpDiscoveryAuthenticator.authenticate(HomeIdpDiscoveryAuthenticator.java:49)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processSingleFlowExecutionModel(DefaultAuthenticationFlow.java:446)
	at org.keycloak.authentication.DefaultAuthenticationFlow.processFlow(DefaultAuthenticationFlow.java:272)
	at org.keycloak.authentication.AuthenticationProcessor.authenticateOnly(AuthenticationProcessor.java:1017)
	at org.keycloak.authentication.AuthenticationProcessor.authenticate(AuthenticationProcessor.java:879)
	at org.keycloak.protocol.AuthorizationEndpointBase.handleBrowserAuthenticationRequest(AuthorizationEndpointBase.java:151)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildAuthorizationCodeAuthorizationResponse(AuthorizationEndpoint.java:338)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.process(AuthorizationEndpoint.java:194)
	at org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint.buildGet(AuthorizationEndpoint.java:112)
	at jdk.internal.reflect.GeneratedMethodAccessor421.invoke(Unknown Source)

```
Keycloak version: 20.0.3
Home IdP Discovery version: V21.2.0
